routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('routes', 'RoutesController');
Route::resource('reserves', 'ReservesController')->only('store');
Auth::routes();

app/Reserve.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reserve extends Model
{
    //
}

app/Route.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Route extends Model
{
    protected $guarded = ['user_id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReservesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use App\Route;
use App\Reserve;

class ReservesController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $routeId = $request->input('route-id');
        $userId = Auth::id();

        $route = Route::where('start', '>', DB::raw("date('now')"))->findOrFail($routeId);
        $reserve = new Reserve();
        $reserve->user_id = $userId;
        $reserve->route_id = $routeId;
        $reserve->save();

        return redirect('/routes');
    }
}

app/Http/Controllers/RoutesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Route;
use App\Http\Requests\RouteRequest;
use Illuminate\Support\Facades\Auth;

class RoutesController extends Controller
{
    public function __construct()
    {
        # $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $routes = Route::all();
        $ctx = ['routes' => $routes];
        return view('routes.index', $ctx);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->role != 'driver') {
            return abort(404);
        }

        return view('routes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(RouteRequest $request)
    {
        $route = new Route($request->all());
        $route->user_id = Auth::id();
        $route->save();

        session()->flash('success', 'Guardado!');
        return redirect('/routes');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::user()->role != 'driver') {
            return abort(404);
        }

        $route = Route::findOrFail($id);
        $ctx = ['route' => $route];
        return view('routes.edit', $ctx);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(RouteRequest $request, $id)
    {
        $route = Route::findOrFail($id);
        $route->update($request->all());

        return redirect('/routes');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
							
							<li class="nav-item">
                                <a class="nav-link" href="{{ route('routes.index') }}">Rotas</a>
                            </li>
							@if (Auth::user()->role == 'driver')
							<li class="nav-item">
                                <a class="nav-link" href="{{ route('routes.create') }}">Adicionar Rota</a>
                            </li>
							@endif
						
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/routes/_form.blade.php
<div class="form-group">
	<label for="route-from">Origem</label>
	<input type="text" name="from" value="{{ old('from', $route->from ?? null) }}" class="form-control" id="route-from">
	@if ($errors->has('from'))
	<span class="error-message">
		<strong>{{ $errors->first('from') }}</strong>
	</span>
	@endif
</div>

<div class="form-group">
	<label for="route-to">Destino</label>
	<input type="text" name="to" value="{{ old('to', $route->to ?? null) }}" class="form-control" id="route-to">
	@if ($errors->has('to'))
	<span class="error-message">
		<strong>{{ $errors->first('to') }}</strong>
	</span>
	@endif
</div>

<div class="form-group">
	<label for="route-start">Partida</label>
	<input type="text" name="start" value="{{ old('start', $route->start ?? null) }}" class="form-control" id="route-start">
	@if ($errors->has('start'))
	<span class="error-message">
		<strong>{{ $errors->first('start') }}</strong>
	</span>
	@endif
</div>

<div class="form-group">
	<label for="route-duration">Duração</label>
	<input type="text" name="duration" value="{{ old('duration', $route->duration ?? null) }}" class="form-control" id="route-duration">
	@if ($errors->has('duration'))
	<span class="error-message">
		<strong>{{ $errors->first('duration') }}</strong>
	</span>
	@endif
</div>

<div class="form-group">
	<label for="route-spots">Lugares</label>
	<input type="text" name="spots" value="{{ old('spots', $route->spots ?? null) }}" class="form-control" id="route-spots">
	@if ($errors->has('spots'))
	<span class="error-message">
		<strong>{{ $errors->first('spots') }}</strong>
	</span>
	@endif
</div>

resources/views/routes/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form action="{{ route('routes.store') }}" method="post">
				@csrf
				{{ method_field('post') }}
				@include('routes._form')
				<button type="submit" class="btn btn-primary">Criar</button>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/routes/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<form action="{{ route('routes.update', $route->id) }}" method="post">
				@csrf
				{{ method_field('put') }}
				@include('routes._form')
				<button type="submit" class="btn btn-primary">Atualizar</button>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/routes/index.blade.php
@extends('layouts.app');

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">Data / Hora</th>
						<th scope="col">Origem</th>
						<th scope="col">Destino</th>
						<th scope="col">Lugares</th>
						<th scope="col">Duração</th>
						<th scope="col">#</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($routes as $route)
					<tr>
						<td>{{ $route->start }}</td>
						<td>{{ $route->from }}</td>
						<td>{{ $route->to }}</td>
						<td>{{ $route->spots }}</td>
						<td>{{ $route->duration }}</td>
						<td>
							<form action="{{ route('reserves.store') }}" method="post">
								@csrf
								{{ method_field('post') }}
								<input type="hidden" name="route-id" value="{{ $route->id }}">
								<button type="submit" class="btn btn-primary">Reservar</button>
							</form>
						</td>
						<tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
		@endsection()